---
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
          version: 6.5.0
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libleveldb-dev libsnappy-dev
      - if: matrix.os == 'windows-latest'
        run: vcpkg install leveldb:x64-windows
      - if: matrix.os != 'windows-latest'
        name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Configure CMake (Windows)
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
name: Build
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
